replicaCount: 1

image:
  repository: kumkammonteju/order-service
  tag: latest  

imagePullPolicy: Always

service:
  type: LoadBalancer
  port: 5003

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

