replicaCount: 1

image:
  repository: kumkammonteju/auth-service
  tag: latest  

imagePullPolicy: Always

service:
  type: LoadBalancer
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

